version: "3"

services:
    web:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-container
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
