version: "3"

services:
    web:
        image: nginx:latest
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-container
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: asiayo_secret

    db:
        image: mysql:5.7
        container_name: mysql-container
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: asiayo_secret
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
